### ISSUE TITLE
print causes hang

### ISSUE THREAD

**Issue by chris-b1** [dmolina/DaemonMode.jl#15]
Running the example below through DaemonMode causes a hang and the following output after a Ctrl+c.  This does not happen if I use `println` instead of `print`

```julia
# repro.jl
print("Hello world")
```

```bash
λ julia --startup-file=no --project=. -e "using DaemonMode; runargs()" repro.jl
hello worldDaemonMode::end
# <Ctrl + c>
Error, cannot connect with server. Is it running?
```

This is on Windows 10, Julia 1.5, DaemonMode 0.1.1

**Comment by dmolina** [comment]
It seems that the juliaserver is not running, have you do the following?

```julia
λ julia --startup-file=no --project=. -e "using DaemonMode; serve()" 
```
previously in another term? The idea is that there is running the server in one process or terminal, and them you run several times runargs() with the file[s] to run. The server is actually which run these files, to accelerate the time, because all functions and packages have been previously run.

**Comment by chris-b1** [comment]
Thanks for the reply @dmolina.  

Yes, the server is running.  When it's not running I get a graceful exit and error message, when it is running it hangs after running `repro.jl`   

I'll take a closer look - given that this happens only with a `print` and not `println` I wonder if there's an assumption of a newline somewhere in the stdout handling

**Comment by chris-b1** [comment]
server
https://github.com/dmolina/DaemonMode.jl/blob/43ff5a7c4eacf7f50fc1936ae6af822b37c0dd9a/src/DaemonMode.jl#L95-L100

client
https://github.com/dmolina/DaemonMode.jl/blob/43ff5a7c4eacf7f50fc1936ae6af822b37c0dd9a/src/DaemonMode.jl#L244-L247 

The issue is that if `run` doesn't end outputting a newline, the last line of the program output will also contain the `token_end`.

**Comment by dmolina** [comment]
Yes, you are right. I have checked now and fixed it in the current master version. I am adding a few new functionality, when I will have I submit a new version. However, now in the  master version it is fixed.
Thank you a lot  for your feedback!
