### ISSUE TITLE
No colored output

### ISSUE THREAD

**Issue by RaulDurand** [dmolina/DaemonMode.jl#17]
First of all, thanks for this incredible package. Certainly, it saves a lot of time from many Julia users.

I installed the package and is working great. The only issue I have is that there is no coloured output. I have a lot of code that print messages as warnings and hints to the terminal.

**Comment by dmolina** [comment]
Thank you for your interest. 

It is possible to have coloured output using the package [Crayons](https://github.com/KristofferC/Crayons.jl) with DaemonMode,  but I do not know why the function printstyled is not working using DaemonMode. 

By the way,  I have just updated the package to give better stacktrace when there is any problem, including the colors.

**Comment by aviatesk** [comment]
@dmolina I guess you need to use `println(IOContext(sock, :color => true), ...)` pattern everywhere ?
