### ISSUE TITLE
Log output in server not in client

### ISSUE THREAD

**Issue by altre** [dmolina/DaemonMode.jl#19]
Thank you for this cool package. I'm using it in combination with dvc, which starts a new julia process for every pipeline step. DaemonMode really helps here and speeds everything up significantly!

One thing I noticed, however:
Any logs written with `@info` are output in the server process, which is a little confusing.

**Comment by dmolina** [comment]
I am glad that you consider useful the package. 
I did not check that behaviour, but thinking about that, it is logical think.  
Maybe I could redirect the logging to the client, but first I need to check if the logging is not redirect to an external file. I have to invest about that. If I learn how to do it, I will indicate in this Issue. Meannwhile, you could redirect the logging to a file, to avoid losing the messages, I recommend package [https://github.com/oxinabox/LoggingExtras.jl](https://github.com/oxinabox/LoggingExtras.jl).

**Comment by dmolina** [comment]
The last version v0.1.3 pending to be Registered shows the logs in the Client without any problem. Check the new [documentation](https://dmolina.github.io/DaemonMode.jl/dev/).
