### ISSUE TITLE
reloading DaemonMode after an update / killing server

### ISSUE THREAD

**Issue by mgr327** [dmolina/DaemonMode.jl#4]
What is the recommended way to reload a running DaemonMode server after the package update?

What is the recommended way to kill a running  DaemonMode server?

Thank you.

**Comment by dmolina** [comment]
Thank you for your interest. 

The recommended way to reload is to kill  a running DaemonMode,  and then run it again the server. 
The recommened way to kill a running DaemonMode server is:

```julia
using DaemonMode
sendExitCode() # or sendExitCode(port) if the port is not the default one.
```
