### ISSUE TITLE
include can cause problems

### ISSUE THREAD

**Issue by feanor12** [dmolina/DaemonMode.jl#6]
I tried to include a local module in a script I ran via DaemonMode and I had some problems.

It seems in the script I have to use something like this to get it to work.
```julia
# instead of
include("../lib.jl")
# I had to use
Base.include(@__MODULE__,"../lib.jl")
```

The reason is that DaemonMode uses a module to encapsulate the code, but there is no local include defined for that module. To include external code one has to include code into the temporary module using Base.include.

Maybe the missing include is also a bug in julia.

**Comment by dmolina** [comment]
Thank you for the feedback. I have not notice it. I will try to fix it.

**Comment by compleathorseplayer** [comment]
I think I discovered an easy fix!!
Just add  the following at the beginning of your program:
include(arg)=Base.include(@__MODULE__,arg)
and everything seems to work.  
[Note this is not function overloading - just appending a method for this situation]

I had a related problem, which I have been trying to fix similarly, but cannot.

When I try to load a saved Neural Network model (built in Flux) using BSON,
I get an undefined reference to NNlib, even if I explicitly load NNlib via  'using NNlib'.
This does not happen in an ordinary sess of Julia

Can you think of any approach to help?

BTW this is a great idea and module!

**Comment by dmolina** [comment]
Thank you for your solution. I  have already included your proposal in the server DaemonMode, and I have register a new version with the fix. Also, now when there is any error the complete stack is shown.

Now you can use "include" function directly in the scripts that use DaemonMode, you do not need to define your include function, DaemonMode is doing that for you before the file is run.
