### ISSUE TITLE
Print full stacktrace when script throws

### ISSUE THREAD

**Issue by XeCycle** [dmolina/DaemonMode.jl#8]
Currently the client only receives a single line about the exception, and that's everything to tell the user.  IMHO we can print a full stacktrace to the socket; I can change it together in #7, but this is going to change behavior more significantly.  So do we want such a change?

**Comment by dmolina** [comment]
Well, depends on the preference of the user. For running a complete script in my opinion current print is enough, but for a script in progress it can be useful.

**Comment by dmolina** [comment]
I am open to accept that change by a optional parameter in serve() method.

**Comment by dmolina** [comment]
Thank you! I have already merged it.
